### ISSUE TITLE
Move swaggerDefinition into a docs folder

### ISSUE THREAD

**Issue by ankushdharkar** [Real-Dev-Squad/website-backend#98]
It should not be in `utils` as it doesn't help us with our code, except than to create documentation

**Comment by pradnyesh45** [comment]
Do I have to create a docs folder, as no folder with the name docs is available. And I have to move the swaggerDefinition file from utils to that new docs folder? I want to work on this issue

**Comment by ankushdharkar** [comment]
That is right @pradnyesh45. Thank you. Assigning this to you.

Are you already part of our Discord server?

**Comment by pradnyesh45** [comment]
No, I am not part of the Discord server.

**Comment by pradnyesh45** [comment]
@ankushdharkar , After running npm start it showed an error of cannot find module '../utils/swaggerDefinition'. I changed the path in generateAPISchema. It still showed the same error when I used npm run test.  
Error: Cannot find module '../utils/swaggerDefinition'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/pradnyesh/Documents/Development/Open-Source/website-backend/middlewares/index.js:9:21)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/pradnyesh/Documents/Development/Open-Source/website-backend/app.js:8:24)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/pradnyesh/Documents/Development/Open-Source/website-backend/server.js:6:13)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/pradnyesh/Documents/Development/Open-Source/website-backend/test/integration/authController.test.js:9:13)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.exports.requireOrImport (/home/pradnyesh/Documents/Development/Open-Source/website-backend/node_modules/mocha/lib/esm-utils.js:20:12)
    at Object.exports.loadFilesAsync (/home/pradnyesh/Documents/Development/Open-Source/website-backend/node_modules/mocha/lib/esm-utils.js:33:34)
    at Mocha.loadFilesAsync (/home/pradnyesh/Documents/Development/Open-Source/website-backend/node_modules/mocha/lib/mocha.js:427:19)
    at singleRun (/home/pradnyesh/Documents/Development/Open-Source/website-backend/node_modules/mocha/lib/cli/run-helpers.js:156:15)
    at exports.runMocha (/home/pradnyesh/Documents/Development/Open-Source/website-backend/node_modules/mocha/lib/cli/run-helpers.js:225:10)
    at Object.exports.handler (/home/pradnyesh/Documents/Development/Open-Source/website-backend/node_modules/mocha/lib/cli/run.js:366:11)
    at innerArgv.then.argv (/home/pradnyesh/Documents/Development/Open-Source/website-backend/node_modules/yargs/lib/command.js:241:49)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:834:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! website-backend@1.0.0 test-integration: `cross-env NODE_ENV=test mocha test/integration/**`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the website-backend@1.0.0 test-integration script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pradnyesh/.npm/_logs/2020-12-15T05_11_54_788Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! website-backend@1.0.0 test: `npm run lint && npm run test-integration && npm run test-unit`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the website-backend@1.0.0 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pradnyesh/.npm/_logs/2020-12-15T05_11_54_838Z-debug.log

**Comment by ankushdharkar** [comment]
@pradnyesh45 Please show us your PR. It's not possible to debug without seeing your changes.

Also, please use [markdown](https://guides.github.com/features/mastering-markdown/) to make it easier to read your message.

You can join our Discord server using [this invite](https://discord.gg/yqU6xxrW)

**Comment by pradnyesh45** [comment]
@ankushdharkar I have created a pull request.

**Comment by pradnyesh45** [comment]
@ankushdharkar The last invite was with the temporary account I guess. I made an account on discord today and Real-dev-squad wasn't there. Can you add me again? My id is #5518

**Comment by swarajpure** [comment]
> 
> 
> @ankushdharkar The last invite was with the temporary account I guess. I made an account on discord today and Real-dev-squad wasn't there. Can you add me again? My id is Pradnyesh Aglawe#5518

Hello, please try [this](https://discord.gg/xr3zJUdX)
If this invite gets expired, please contact me on LinkedIn https://www.linkedin.com/in/swarajrajpure/

**Comment by swarajpure** [comment]
@pradnyesh45 Any updates?

**Comment by pradnyesh45** [comment]
@swarajpure Yes, I have joined the discord server.
About the issue, I haven't worked on it after that.

**Comment by swarajpure** [comment]
> 
> 
> @swarajpure Yes, I have joined the discord server.
> About the issue, I haven't worked on it after that.

Cool. Please send a PR with the changes you've done. So we can see whole of your code and help you out 😄

**Comment by swarajpure** [comment]
Please do a global search for `swaggerDefinition` and change the pathname accordingly wherever required. 

Also, you're supposed to run `npm run dev` as it is for development purposes. `npm run start` is for production.
